name: jumpbox

instance_groups:
- name: jumpbox
  instances: 1
  azs:       [z1]
  stemcell:  default
  vm_resources:
    cpu: 2
    ram: 2048
    ephemeral_disk_size: 40_960
  networks:
    - name: default
  jobs:
    - { release: jumpbox, name: jumpbox }
    - { release: jumpbox, name: inventory }
  env:
    bosh:
      remove_dev_tools: false


update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
- alias:   default
  os:      ubuntu-jammy
  version: latest

releases:
- name:    jumpbox
  version: 5.0.4
  url:     https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v5.0.4/jumpbox-5.0.4.tgz
  sha1:    0171ee501d91587cd76126cd57f715113040f6a9
