name: jumpbox

instance_groups:
- name: jumpbox
  instances: 1
  azs:       [z1]
  stemcell:  default
  vm_resources:
    cpu: 2
    ram: 2048
    ephemeral_disk_size: 40_960
  networks:
    - name: default
  jobs:
    - { release: jumpbox, name: jumpbox }
    - { release: jumpbox, name: inventory }

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
- alias:   default
  os:      ubuntu-jammy
  version: latest

releases:
- name:    jumpbox
  version: 4.13.0
  url:     https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v4.13.0/jumpbox-4.13.0.tgz
  sha1:    7ece1417fad641823fe824e0340e4d90c1225c21
