---
meta:
  name:    jumpbox
  release: Jumpbox
  target:  pipes/cloudfoundry-community
  url:     https://pipes.scalecf.net

  test-errand: inventory

  manifest:
    path: ci/manifest.yml

  git:
    name:  Cloudfoundry Community CI Bot
    email: ci@cloudfoundry-community.org

  bosh-lite:
    target:   ((thunder-dome.url))
    username: ((thunder-dome.username))
    password: ((thunder-dome.password))
    cacert:   ((thunder-dome.ca-certificate))

  aws:
    access_key: ((aws.access_key_id))
    secret_key: ((aws.secret_access_key))

  github:
    owner:        cloudfoundry-community
    repo:         jumpbox-boshrelease
    branch:       main
    private_key:  ((github.private_key))
    access_token: ((github.access_token_rw))

  shout:
    url:      ((shout.url))
    username: ((shout.username))
    password: ((shout.password))
